[package]
name = "hikaru"
version = "0.1.0"
authors = ["Eli Ben-Porat <github@ben-porat.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
serde = {version = "1.0", features=["derive"]}
serde_json = {version = "1.0"}
